// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Minusix
{
    internal sealed partial class Vsix
    {
        public const string Id = "Minusix.bde10d6d-1d02-41e5-aa48-ef04c07f8264";
        public const string Name = "Minusix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "정범 조";
        public const string Tags = "";
    }
}
